functionsDirectory = "C:\\Users\\basto\\OneDrive\\Prototipos de site\\_deploy\\vivian-torres\\netlify\\functions"
functionsDirectoryOrigin = "config"
headersOrigin = "config"
plugins = []
redirects = []

[build]
publish = "C:\\Users\\basto\\OneDrive\\Prototipos de site\\_deploy\\vivian-torres"
publishOrigin = "default"
base = "C:\\Users\\basto\\OneDrive\\Prototipos de site\\_deploy\\vivian-torres"
functions = "C:\\Users\\basto\\OneDrive\\Prototipos de site\\_deploy\\vivian-torres\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[headers]]
for = "/*"

[headers.values]
Access-Control-Allow-Origin = "*"